.PHONY: assets assets-probe assets-validate assets-doctor assets-status assets-icons

assets:
	7dtd-assets build

assets-probe:
	7dtd-assets build --probe

assets-validate:
	7dtd-assets validate
	7dtd-assets check-icons

assets-icons:
	7dtd-assets check-icons

assets-doctor:
	7dtd-assets doctor

assets-status:
	7dtd-assets status
