using System.Collections.Generic;
using UnityEngine;
using ZdtdPlaytest;

// Generated by `shamway acceptance-provider` for ShamwaySelfTest. Edit the
// generator, not this file: it is rewritten on every run.
//
// This is the half of bundle acceptance that no offline gate can reach. A
// Unity runtime of the game's revision loading the bundle (`shamway
// verify-bundle`) proves construction; it does not run the game's own
// resolution chain — DataLoader.ParseDataPathIdentifier rewriting
// @modfolder(Name), AssetBundleManager.LoadAssetBundle opening the archive,
// and AssetBundleManager._get reducing an asset request to its file-name
// stem. These cases run that chain inside the live client, so a pass is the
// game itself saying it can read what this pipeline staged.
//
// It still proves nothing about how the asset looks or sounds. That remains a
// person's judgement, recorded with `shamway client capture`.
public sealed class ShamwaySelfTestAcceptanceProvider : IScenarioProvider
{
    private const string Bundle =
        "#@modfolder(ShamwaySelfTest):Resources/shamwayselftest.unity3d";

    public IEnumerable<string> SuiteIds
    {
        get
        {
            yield return "shamwayselftest_bundle";
            yield return "shamwayselftest_look";
        }
    }

    public void AppendSuite(List<CaseDef> queue, string suite, int lap)
    {
        RejectMixedVisualSuites();
        string label = lap > 0 ? suite + "@" + lap : suite;
        if (suite == "shamwayselftest_look")
        {

        GameObject shamwaySelfTestPropStaged = null;
        queue.Add(CaseDef.Staged(label, "look_shamwaySelfTestProp", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestProp");
                if (prefab == null)
                {
                    Report.Info("shamwaySelfTestProp: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "shamwaySelfTestProp: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                shamwaySelfTestPropStaged = UnityEngine.Object.Instantiate(prefab);
                shamwaySelfTestPropStaged.transform.position = camera.position + ahead * 3.5f;
                // Face the camera, and keep the prop's own up axis upright so
                // the orientation card is readable rather than lying on edge.
                shamwaySelfTestPropStaged.transform.rotation =
                    Quaternion.LookRotation(-ahead, Vector3.up);
                var renderers = shamwaySelfTestPropStaged.GetComponentsInChildren<Renderer>(true);
                Report.Info("shamwaySelfTestProp: staged at " + shamwaySelfTestPropStaged.transform.position
                    + ", camera at " + camera.position
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage shamwaySelfTestProp in front of the camera"));
            return;
        }


        GameObject shamwaySelfTestPropLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestPropLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestProp");
                var loaded = shamwaySelfTestPropLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp: LoadAsset<GameObject> returned null"
                    : "shamwaySelfTestProp: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestPropLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp" && loaded.transform != null;
            },
            fail: "the game did not load shamwaySelfTestProp from the staged bundle"));

        Mesh shamwaySelfTestProp_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp_mesh", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestProp_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?shamwaySelfTestProp_mesh");
                var loaded = shamwaySelfTestProp_meshLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp_mesh: LoadAsset<Mesh> returned null"
                    : "shamwaySelfTestProp_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestProp_meshLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load shamwaySelfTestProp_mesh from the staged bundle"));

        Material shamwaySelfTestProp_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp_mat", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestProp_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?shamwaySelfTestProp_mat");
                var loaded = shamwaySelfTestProp_matLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp_mat: LoadAsset<Material> returned null"
                    : "shamwaySelfTestProp_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestProp_matLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp_mat" && loaded.shader != null;
            },
            fail: "the game did not load shamwaySelfTestProp_mat from the staged bundle"));

        Texture2D shamwaySelfTestProp_albedoLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp_albedo", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestProp_albedoLoaded = DataLoader.LoadAsset<Texture2D>(Bundle + "?shamwaySelfTestProp_albedo");
                var loaded = shamwaySelfTestProp_albedoLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp_albedo: LoadAsset<Texture2D> returned null"
                    : "shamwaySelfTestProp_albedo: " + loaded.name + " " + loaded.width + "x" + loaded.height + " " + loaded.format);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestProp_albedoLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp_albedo" && loaded.width > 0 && loaded.height > 0;
            },
            fail: "the game did not load shamwaySelfTestProp_albedo from the staged bundle"));

        // A stem the bundle does not contain must still come back null, so a
        // pass above cannot be a loader that answers every request.
        Object absent = null;
        queue.Add(CaseDef.Live(label, "absent_stem_is_null", new[] { "bundle" },
            act: ctx =>
            {
                absent = DataLoader.LoadAsset<Object>(Bundle + "?shamwayAbsentStemProbe");
                Report.Info("absent_stem: " + (absent == null ? "null (expected)" : absent.name));
            },
            assert: ctx => absent == null,
            fail: "a stem the bundle does not contain resolved to an object"));
    }

    // A prefab hanging in front of the camera (*_look) and a block sitting on
    // a voxel (*_block_*) are different pictures. Mixing them in one
    // PLAYTEST_SUITE list is how a self-test rendered a texture mid-air AND a
    // placed block in the same session. Refuse it here, not after someone has
    // already watched both.
    static void RejectMixedVisualSuites()
    {
        var raw = System.Environment.GetEnvironmentVariable("PLAYTEST_SUITE") ?? "";
        bool look = false, block = false;
        foreach (var token in raw.Split(new char[] { ',', ';', ' ', '\t' },
                     System.StringSplitOptions.RemoveEmptyEntries))
        {
            if (token.EndsWith("_look")) look = true;
            if (token.IndexOf("_block_", System.StringComparison.Ordinal) >= 0) block = true;
        }
        if (look && block)
        {
            throw new System.InvalidOperationException(
                "PLAYTEST_SUITE mixes a prefab-look suite (*_look) and a "
                + "block-placement suite (*_block_*); they are different pictures. "
                + "Run them as separate playtest invocations.");
        }
    }
}
