using System.Collections.Generic;
using UnityEngine;
using ZdtdPlaytest;

// Generated by `shamway acceptance-provider` for ShamwaySelfTest. Edit the
// generator, not this file: it is rewritten on every run.
//
// This is the half of bundle acceptance that no offline gate can reach. A
// Unity runtime of the game's revision loading the bundle (`shamway
// verify-bundle`) proves construction; it does not run the game's own
// resolution chain — DataLoader.ParseDataPathIdentifier rewriting
// @modfolder(Name), AssetBundleManager.LoadAssetBundle opening the archive,
// and AssetBundleManager._get reducing an asset request to its file-name
// stem. These cases run that chain inside the live client, so a pass is the
// game itself saying it can read what this pipeline staged.
//
// It still proves nothing about how the asset looks or sounds. That remains a
// person's judgement, recorded with `shamway client capture`.
public sealed class ShamwaySelfTestAcceptanceProvider : IScenarioProvider
{
    private const string Bundle =
        "#@modfolder(ShamwaySelfTest):Resources/shamwayselftest.unity3d";

    public IEnumerable<string> SuiteIds
    {
        get
        {
            yield return "shamwayselftest_bundle";
            yield return "shamwayselftest_burst_look";
            yield return "shamwayselftest_gear_look";
            yield return "shamwayselftest_shamwayselftestarachnid_look";
            yield return "shamwayselftest_shamwayselftestbird_look";
            yield return "shamwayselftest_shamwayselftestcreature_look";
            yield return "shamwayselftest_shamwayselftestdino_look";
            yield return "shamwayselftest_shamwayselftestprop_look";
            yield return "shamwayselftest_timednuke_look";
        }
    }

    public void AppendSuite(List<CaseDef> queue, string suite, int lap)
    {
        RejectMixedVisualSuites();
        string label = lap > 0 ? suite + "@" + lap : suite;
        if (suite == "shamwayselftest_burst_look")
        {

        GameObject burstStaged = null;
        queue.Add(CaseDef.Staged(label, "look_burst", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?burst");
                if (prefab == null)
                {
                    Report.Info("burst: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "burst: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                burstStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(burstStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                burstStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = burstStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                burstStaged.transform.position = placed;
                Report.Info("burst: staged at " + burstStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage burst in front of the camera"));
            return;
        }
if (suite == "shamwayselftest_gear_look")
        {

        GameObject gearStaged = null;
        queue.Add(CaseDef.Staged(label, "look_gear", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?gear");
                if (prefab == null)
                {
                    Report.Info("gear: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "gear: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                gearStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(gearStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                gearStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = gearStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                gearStaged.transform.position = placed;
                Report.Info("gear: staged at " + gearStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage gear in front of the camera"));
            return;
        }
if (suite == "shamwayselftest_shamwayselftestarachnid_look")
        {

        GameObject shamwaySelfTestArachnidStaged = null;
        queue.Add(CaseDef.Staged(label, "look_shamwaySelfTestArachnid", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestArachnid");
                if (prefab == null)
                {
                    Report.Info("shamwaySelfTestArachnid: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "shamwaySelfTestArachnid: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                shamwaySelfTestArachnidStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(shamwaySelfTestArachnidStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                shamwaySelfTestArachnidStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = shamwaySelfTestArachnidStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                shamwaySelfTestArachnidStaged.transform.position = placed;
                Report.Info("shamwaySelfTestArachnid: staged at " + shamwaySelfTestArachnidStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage shamwaySelfTestArachnid in front of the camera"));
            return;
        }
if (suite == "shamwayselftest_shamwayselftestbird_look")
        {

        GameObject shamwaySelfTestBirdStaged = null;
        queue.Add(CaseDef.Staged(label, "look_shamwaySelfTestBird", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestBird");
                if (prefab == null)
                {
                    Report.Info("shamwaySelfTestBird: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "shamwaySelfTestBird: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                shamwaySelfTestBirdStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(shamwaySelfTestBirdStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                shamwaySelfTestBirdStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = shamwaySelfTestBirdStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                shamwaySelfTestBirdStaged.transform.position = placed;
                Report.Info("shamwaySelfTestBird: staged at " + shamwaySelfTestBirdStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage shamwaySelfTestBird in front of the camera"));
            return;
        }
if (suite == "shamwayselftest_shamwayselftestcreature_look")
        {

        GameObject shamwaySelfTestCreatureStaged = null;
        queue.Add(CaseDef.StagedClip(
            label, "motion_shamwaySelfTestCreature", new[] { "capture", "bundle", "clip" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestCreature");
                if (prefab == null)
                {
                    Report.Info("shamwaySelfTestCreature: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "shamwaySelfTestCreature: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                shamwaySelfTestCreatureStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(shamwaySelfTestCreatureStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                shamwaySelfTestCreatureStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = shamwaySelfTestCreatureStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                shamwaySelfTestCreatureStaged.transform.position = placed;
                Report.Info("shamwaySelfTestCreature: staged at " + shamwaySelfTestCreatureStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            onHold: (ctx, holdFraction) =>
            {
                var staged = shamwaySelfTestCreatureStaged;
                if (staged == null) return;
                // One full turn over the hold: 360 degrees across 12 seconds.
                staged.transform.Rotate(0f, 360f * Time.deltaTime / 12f, 0f);
            },
            fail: "could not stage shamwaySelfTestCreature for its motion clip"));
            return;
        }
if (suite == "shamwayselftest_shamwayselftestdino_look")
        {

        GameObject shamwaySelfTestDinoStaged = null;
        queue.Add(CaseDef.Staged(label, "look_shamwaySelfTestDino", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestDino");
                if (prefab == null)
                {
                    Report.Info("shamwaySelfTestDino: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "shamwaySelfTestDino: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                shamwaySelfTestDinoStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(shamwaySelfTestDinoStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                shamwaySelfTestDinoStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = shamwaySelfTestDinoStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                shamwaySelfTestDinoStaged.transform.position = placed;
                Report.Info("shamwaySelfTestDino: staged at " + shamwaySelfTestDinoStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage shamwaySelfTestDino in front of the camera"));
            return;
        }
if (suite == "shamwayselftest_shamwayselftestprop_look")
        {

        GameObject shamwaySelfTestPropStaged = null;
        queue.Add(CaseDef.Staged(label, "look_shamwaySelfTestProp", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestProp");
                if (prefab == null)
                {
                    Report.Info("shamwaySelfTestProp: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "shamwaySelfTestProp: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                shamwaySelfTestPropStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(shamwaySelfTestPropStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                shamwaySelfTestPropStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = shamwaySelfTestPropStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                shamwaySelfTestPropStaged.transform.position = placed;
                Report.Info("shamwaySelfTestProp: staged at " + shamwaySelfTestPropStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage shamwaySelfTestProp in front of the camera"));
            return;
        }
if (suite == "shamwayselftest_timednuke_look")
        {

        GameObject timedNukeStaged = null;
        queue.Add(CaseDef.Staged(label, "look_timedNuke", new[] { "capture", "bundle" },
            stage: ctx =>
            {
                var prefab = DataLoader.LoadAsset<GameObject>(Bundle + "?timedNuke");
                if (prefab == null)
                {
                    Report.Info("timedNuke: LoadAsset<GameObject> returned null; nothing to stage");
                    return false;
                }
                var player = ctx == null ? null : ctx.Player;
                if (player == null)
                {
                    Report.Info(
                        "timedNuke: no local player, so there is no camera to stage in front of");
                    return false;
                }
                // In front of the *camera*, not the player's feet. An
                // EntityPlayerLocal's `position` is its ground position and its
                // own transform faces its body, so a prop placed from those
                // lands under the camera and out of frame - which is exactly
                // what the first staged capture photographed: an empty scene
                // that still passed, because the case only asks whether a
                // renderer exists.
                var camera = player.playerCamera != null
                    ? player.playerCamera.transform
                    : player.transform;
                var ahead = camera.forward;
                timedNukeStaged = UnityEngine.Object.Instantiate(prefab);
                CaseDef.RegisterStaged(timedNukeStaged);
                // Face the camera with yaw only, keeping the prop's own up
                // axis upright. `LookRotation(-ahead, up)` looks right but
                // pitches the prop by the camera's own pitch, and a staged
                // quadruped's camera looks down at it — a 25° lean put the
                // front feet ~0.17 m below the rear feet, and grounding by
                // the unrotated lowest point then sank the front legs into
                // the floor ("clipped as fuck", twice). Yaw-only keeps every
                // foot at one height, so the lowest bound point is the
                // standing surface.
                var yaw = Mathf.Atan2(-ahead.x, -ahead.z) * Mathf.Rad2Deg;
                timedNukeStaged.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
                var placed = camera.position + ahead * 3.5f;
                // Sit the prefab on the ground instead of hovering at the
                // camera offset: an animated entity's motion reads against
                // the terrain, not against empty sky, and a floating prop
                // looks like a staging bug. Drop it onto the actual surface
                // with a physics raycast straight down from the staging
                // point, using the game's own ground mask (the fall-point
                // check in the game raycasts with 268500992 = layers
                // 13+15+28, the traversable voxel surface; verified from
                // Assembly-CSharp). The staged prefab has no colliders of
                // its own, so the hit is the world surface at that column —
                // slopes and carved pits included, in the same transform
                // space as the camera. The terrain-height APIs failed this
                // live twice before the raycast: `GetHeightAt` is the
                // uncarved generator heightmap, and `GetTerrainHeight`
                // needs an `Origin.position` rebase plus a loaded chunk —
                // both grounded the staged entity wrong.
                var renderers = timedNukeStaged.GetComponentsInChildren<Renderer>(true);
                float lowest = 0f;
                float ground = 0f;
                if (renderers.Length > 0)
                {
                    var bounds = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++)
                        bounds.Encapsulate(renderers[i].bounds);
                    lowest = bounds.min.y;
                    var world = GameManager.Instance != null ? GameManager.Instance.World : null;
                    if (world != null)
                    {
                        // The game's own ground placement, from the IL: ground
                        // entities spawn at `chunk.GetHeight(blockX, blockZ)
                        // + 1` (World.FindRandomSpawnPointNearPosition), and
                        // `World.GetHeight(worldX, worldZ)` resolves to that
                        // same chunk height map — the actual top block.
                        // `World.GetTerrainHeight` (m_TerrainHeight) is the
                        // terrain generator's cached height and sits ~2
                        // blocks under the visible surface in carved terrain,
                        // which is how this entity ended up knee-deep in the
                        // floor. Terrain APIs take ABSOLUTE world coordinates
                        // while transforms are rebased by Origin.position
                        // (Entity.transform.position = position -
                        // Origin.position), so the staging point is converted
                        // before the query; a raycast on the ground mask is
                        // the fallback when the chunk is not loaded yet.
                        var abs = placed + Origin.position;
                        ground = world.GetHeight((int)abs.x, (int)abs.z) + 1f;
                        if (ground > 1f)
                            placed.y = ground - Origin.position.y - lowest;
                        else if (Physics.Raycast(placed, Vector3.down, out var groundHit, 200f, 268500992))
                            placed.y = groundHit.point.y - lowest;
                    }
                }
                timedNukeStaged.transform.position = placed;
                Report.Info("timedNuke: staged at " + timedNukeStaged.transform.position
                    + ", camera at " + camera.position
                    + ", ground=" + ground + " lowest=" + lowest
                    + ", with " + renderers.Length + " renderer(s)");
                // A prefab with no renderer cannot be photographed into evidence.
                return renderers.Length > 0;
            },
            holdSeconds: 12f,
            fail: "could not stage timedNuke in front of the camera"));
            return;
        }


        GameObject burstLoaded = null;
        queue.Add(CaseDef.Live(label, "load_burst", new[] { "bundle" },
            act: ctx =>
            {
                burstLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?burst");
                var loaded = burstLoaded;
                Report.Info(loaded == null
                    ? "burst: LoadAsset<GameObject> returned null"
                    : "burst: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = burstLoaded;
                return loaded != null && loaded.name == "burst" && loaded.transform != null;
            },
            fail: "the game did not load burst from the staged bundle"));

        Material flashMatLoaded = null;
        queue.Add(CaseDef.Live(label, "load_flashMat", new[] { "bundle" },
            act: ctx =>
            {
                flashMatLoaded = DataLoader.LoadAsset<Material>(Bundle + "?flashMat");
                var loaded = flashMatLoaded;
                Report.Info(loaded == null
                    ? "flashMat: LoadAsset<Material> returned null"
                    : "flashMat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = flashMatLoaded;
                return loaded != null && loaded.name == "flashMat" && loaded.shader != null;
            },
            fail: "the game did not load flashMat from the staged bundle"));

        Material smokeMatLoaded = null;
        queue.Add(CaseDef.Live(label, "load_smokeMat", new[] { "bundle" },
            act: ctx =>
            {
                smokeMatLoaded = DataLoader.LoadAsset<Material>(Bundle + "?smokeMat");
                var loaded = smokeMatLoaded;
                Report.Info(loaded == null
                    ? "smokeMat: LoadAsset<Material> returned null"
                    : "smokeMat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = smokeMatLoaded;
                return loaded != null && loaded.name == "smokeMat" && loaded.shader != null;
            },
            fail: "the game did not load smokeMat from the staged bundle"));

        Material sparkMatLoaded = null;
        queue.Add(CaseDef.Live(label, "load_sparkMat", new[] { "bundle" },
            act: ctx =>
            {
                sparkMatLoaded = DataLoader.LoadAsset<Material>(Bundle + "?sparkMat");
                var loaded = sparkMatLoaded;
                Report.Info(loaded == null
                    ? "sparkMat: LoadAsset<Material> returned null"
                    : "sparkMat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = sparkMatLoaded;
                return loaded != null && loaded.name == "sparkMat" && loaded.shader != null;
            },
            fail: "the game did not load sparkMat from the staged bundle"));

        Texture2D flashCardLoaded = null;
        queue.Add(CaseDef.Live(label, "load_flashCard", new[] { "bundle" },
            act: ctx =>
            {
                flashCardLoaded = DataLoader.LoadAsset<Texture2D>(Bundle + "?flashCard");
                var loaded = flashCardLoaded;
                Report.Info(loaded == null
                    ? "flashCard: LoadAsset<Texture2D> returned null"
                    : "flashCard: " + loaded.name + " " + loaded.width + "x" + loaded.height + " " + loaded.format);
            },
            assert: ctx =>
            {
                var loaded = flashCardLoaded;
                return loaded != null && loaded.name == "flashCard" && loaded.width > 0 && loaded.height > 0;
            },
            fail: "the game did not load flashCard from the staged bundle"));

        GameObject gearLoaded = null;
        queue.Add(CaseDef.Live(label, "load_gear", new[] { "bundle" },
            act: ctx =>
            {
                gearLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?gear");
                var loaded = gearLoaded;
                Report.Info(loaded == null
                    ? "gear: LoadAsset<GameObject> returned null"
                    : "gear: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = gearLoaded;
                return loaded != null && loaded.name == "gear" && loaded.transform != null;
            },
            fail: "the game did not load gear from the staged bundle"));

        Mesh gear_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_gear_mesh", new[] { "bundle" },
            act: ctx =>
            {
                gear_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?gear_mesh");
                var loaded = gear_meshLoaded;
                Report.Info(loaded == null
                    ? "gear_mesh: LoadAsset<Mesh> returned null"
                    : "gear_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = gear_meshLoaded;
                return loaded != null && loaded.name == "gear_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load gear_mesh from the staged bundle"));

        Material gear_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_gear_mat", new[] { "bundle" },
            act: ctx =>
            {
                gear_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?gear_mat");
                var loaded = gear_matLoaded;
                Report.Info(loaded == null
                    ? "gear_mat: LoadAsset<Material> returned null"
                    : "gear_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = gear_matLoaded;
                return loaded != null && loaded.name == "gear_mat" && loaded.shader != null;
            },
            fail: "the game did not load gear_mat from the staged bundle"));

        GameObject shamwaySelfTestArachnidLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestArachnid", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestArachnidLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestArachnid");
                var loaded = shamwaySelfTestArachnidLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestArachnid: LoadAsset<GameObject> returned null"
                    : "shamwaySelfTestArachnid: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestArachnidLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestArachnid" && loaded.transform != null;
            },
            fail: "the game did not load shamwaySelfTestArachnid from the staged bundle"));

        Mesh shamwaySelfTestArachnid_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestArachnid_mesh", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestArachnid_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?shamwaySelfTestArachnid_mesh");
                var loaded = shamwaySelfTestArachnid_meshLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestArachnid_mesh: LoadAsset<Mesh> returned null"
                    : "shamwaySelfTestArachnid_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestArachnid_meshLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestArachnid_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load shamwaySelfTestArachnid_mesh from the staged bundle"));

        Material shamwaySelfTestArachnid_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestArachnid_mat", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestArachnid_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?shamwaySelfTestArachnid_mat");
                var loaded = shamwaySelfTestArachnid_matLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestArachnid_mat: LoadAsset<Material> returned null"
                    : "shamwaySelfTestArachnid_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestArachnid_matLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestArachnid_mat" && loaded.shader != null;
            },
            fail: "the game did not load shamwaySelfTestArachnid_mat from the staged bundle"));

        GameObject shamwaySelfTestBirdLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestBird", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestBirdLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestBird");
                var loaded = shamwaySelfTestBirdLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestBird: LoadAsset<GameObject> returned null"
                    : "shamwaySelfTestBird: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestBirdLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestBird" && loaded.transform != null;
            },
            fail: "the game did not load shamwaySelfTestBird from the staged bundle"));

        Mesh shamwaySelfTestBird_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestBird_mesh", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestBird_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?shamwaySelfTestBird_mesh");
                var loaded = shamwaySelfTestBird_meshLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestBird_mesh: LoadAsset<Mesh> returned null"
                    : "shamwaySelfTestBird_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestBird_meshLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestBird_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load shamwaySelfTestBird_mesh from the staged bundle"));

        Material shamwaySelfTestBird_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestBird_mat", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestBird_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?shamwaySelfTestBird_mat");
                var loaded = shamwaySelfTestBird_matLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestBird_mat: LoadAsset<Material> returned null"
                    : "shamwaySelfTestBird_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestBird_matLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestBird_mat" && loaded.shader != null;
            },
            fail: "the game did not load shamwaySelfTestBird_mat from the staged bundle"));

        TextAsset shamwaySelfTestCreatureanimLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestCreature.anim", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestCreatureanimLoaded = DataLoader.LoadAsset<TextAsset>(Bundle + "?shamwaySelfTestCreature.anim");
                var loaded = shamwaySelfTestCreatureanimLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestCreature.anim: LoadAsset<TextAsset> returned null"
                    : "shamwaySelfTestCreature.anim: " + loaded.name + " bytes=" + loaded.bytes.Length);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestCreatureanimLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestCreature.anim" && loaded.text != null;
            },
            fail: "the game did not load shamwaySelfTestCreature.anim from the staged bundle"));

        GameObject shamwaySelfTestCreatureLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestCreature", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestCreatureLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestCreature");
                var loaded = shamwaySelfTestCreatureLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestCreature: LoadAsset<GameObject> returned null"
                    : "shamwaySelfTestCreature: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestCreatureLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestCreature" && loaded.transform != null;
            },
            fail: "the game did not load shamwaySelfTestCreature from the staged bundle"));

        Mesh shamwaySelfTestCreature_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestCreature_mesh", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestCreature_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?shamwaySelfTestCreature_mesh");
                var loaded = shamwaySelfTestCreature_meshLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestCreature_mesh: LoadAsset<Mesh> returned null"
                    : "shamwaySelfTestCreature_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestCreature_meshLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestCreature_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load shamwaySelfTestCreature_mesh from the staged bundle"));

        Material shamwaySelfTestCreature_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestCreature_mat", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestCreature_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?shamwaySelfTestCreature_mat");
                var loaded = shamwaySelfTestCreature_matLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestCreature_mat: LoadAsset<Material> returned null"
                    : "shamwaySelfTestCreature_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestCreature_matLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestCreature_mat" && loaded.shader != null;
            },
            fail: "the game did not load shamwaySelfTestCreature_mat from the staged bundle"));

        Texture2D shamwaySelfTestCreature_albedoLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestCreature_albedo", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestCreature_albedoLoaded = DataLoader.LoadAsset<Texture2D>(Bundle + "?shamwaySelfTestCreature_albedo");
                var loaded = shamwaySelfTestCreature_albedoLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestCreature_albedo: LoadAsset<Texture2D> returned null"
                    : "shamwaySelfTestCreature_albedo: " + loaded.name + " " + loaded.width + "x" + loaded.height + " " + loaded.format);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestCreature_albedoLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestCreature_albedo" && loaded.width > 0 && loaded.height > 0;
            },
            fail: "the game did not load shamwaySelfTestCreature_albedo from the staged bundle"));

        GameObject shamwaySelfTestDinoLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestDino", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestDinoLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestDino");
                var loaded = shamwaySelfTestDinoLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestDino: LoadAsset<GameObject> returned null"
                    : "shamwaySelfTestDino: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestDinoLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestDino" && loaded.transform != null;
            },
            fail: "the game did not load shamwaySelfTestDino from the staged bundle"));

        Mesh shamwaySelfTestDino_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestDino_mesh", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestDino_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?shamwaySelfTestDino_mesh");
                var loaded = shamwaySelfTestDino_meshLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestDino_mesh: LoadAsset<Mesh> returned null"
                    : "shamwaySelfTestDino_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestDino_meshLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestDino_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load shamwaySelfTestDino_mesh from the staged bundle"));

        Material shamwaySelfTestDino_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestDino_mat", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestDino_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?shamwaySelfTestDino_mat");
                var loaded = shamwaySelfTestDino_matLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestDino_mat: LoadAsset<Material> returned null"
                    : "shamwaySelfTestDino_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestDino_matLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestDino_mat" && loaded.shader != null;
            },
            fail: "the game did not load shamwaySelfTestDino_mat from the staged bundle"));

        GameObject shamwaySelfTestPropLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestPropLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?shamwaySelfTestProp");
                var loaded = shamwaySelfTestPropLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp: LoadAsset<GameObject> returned null"
                    : "shamwaySelfTestProp: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestPropLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp" && loaded.transform != null;
            },
            fail: "the game did not load shamwaySelfTestProp from the staged bundle"));

        Mesh shamwaySelfTestProp_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp_mesh", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestProp_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?shamwaySelfTestProp_mesh");
                var loaded = shamwaySelfTestProp_meshLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp_mesh: LoadAsset<Mesh> returned null"
                    : "shamwaySelfTestProp_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestProp_meshLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load shamwaySelfTestProp_mesh from the staged bundle"));

        Material shamwaySelfTestProp_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp_mat", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestProp_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?shamwaySelfTestProp_mat");
                var loaded = shamwaySelfTestProp_matLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp_mat: LoadAsset<Material> returned null"
                    : "shamwaySelfTestProp_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestProp_matLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp_mat" && loaded.shader != null;
            },
            fail: "the game did not load shamwaySelfTestProp_mat from the staged bundle"));

        Texture2D shamwaySelfTestProp_albedoLoaded = null;
        queue.Add(CaseDef.Live(label, "load_shamwaySelfTestProp_albedo", new[] { "bundle" },
            act: ctx =>
            {
                shamwaySelfTestProp_albedoLoaded = DataLoader.LoadAsset<Texture2D>(Bundle + "?shamwaySelfTestProp_albedo");
                var loaded = shamwaySelfTestProp_albedoLoaded;
                Report.Info(loaded == null
                    ? "shamwaySelfTestProp_albedo: LoadAsset<Texture2D> returned null"
                    : "shamwaySelfTestProp_albedo: " + loaded.name + " " + loaded.width + "x" + loaded.height + " " + loaded.format);
            },
            assert: ctx =>
            {
                var loaded = shamwaySelfTestProp_albedoLoaded;
                return loaded != null && loaded.name == "shamwaySelfTestProp_albedo" && loaded.width > 0 && loaded.height > 0;
            },
            fail: "the game did not load shamwaySelfTestProp_albedo from the staged bundle"));

        Texture2D smokeCardLoaded = null;
        queue.Add(CaseDef.Live(label, "load_smokeCard", new[] { "bundle" },
            act: ctx =>
            {
                smokeCardLoaded = DataLoader.LoadAsset<Texture2D>(Bundle + "?smokeCard");
                var loaded = smokeCardLoaded;
                Report.Info(loaded == null
                    ? "smokeCard: LoadAsset<Texture2D> returned null"
                    : "smokeCard: " + loaded.name + " " + loaded.width + "x" + loaded.height + " " + loaded.format);
            },
            assert: ctx =>
            {
                var loaded = smokeCardLoaded;
                return loaded != null && loaded.name == "smokeCard" && loaded.width > 0 && loaded.height > 0;
            },
            fail: "the game did not load smokeCard from the staged bundle"));

        Texture2D sparkCardLoaded = null;
        queue.Add(CaseDef.Live(label, "load_sparkCard", new[] { "bundle" },
            act: ctx =>
            {
                sparkCardLoaded = DataLoader.LoadAsset<Texture2D>(Bundle + "?sparkCard");
                var loaded = sparkCardLoaded;
                Report.Info(loaded == null
                    ? "sparkCard: LoadAsset<Texture2D> returned null"
                    : "sparkCard: " + loaded.name + " " + loaded.width + "x" + loaded.height + " " + loaded.format);
            },
            assert: ctx =>
            {
                var loaded = sparkCardLoaded;
                return loaded != null && loaded.name == "sparkCard" && loaded.width > 0 && loaded.height > 0;
            },
            fail: "the game did not load sparkCard from the staged bundle"));

        GameObject timedNukeLoaded = null;
        queue.Add(CaseDef.Live(label, "load_timedNuke", new[] { "bundle" },
            act: ctx =>
            {
                timedNukeLoaded = DataLoader.LoadAsset<GameObject>(Bundle + "?timedNuke");
                var loaded = timedNukeLoaded;
                Report.Info(loaded == null
                    ? "timedNuke: LoadAsset<GameObject> returned null"
                    : "timedNuke: " + loaded.name + " children=" + loaded.transform.childCount + " renderers=" + loaded.GetComponentsInChildren<Renderer>(true).Length);
            },
            assert: ctx =>
            {
                var loaded = timedNukeLoaded;
                return loaded != null && loaded.name == "timedNuke" && loaded.transform != null;
            },
            fail: "the game did not load timedNuke from the staged bundle"));

        Mesh timedNuke_meshLoaded = null;
        queue.Add(CaseDef.Live(label, "load_timedNuke_mesh", new[] { "bundle" },
            act: ctx =>
            {
                timedNuke_meshLoaded = DataLoader.LoadAsset<Mesh>(Bundle + "?timedNuke_mesh");
                var loaded = timedNuke_meshLoaded;
                Report.Info(loaded == null
                    ? "timedNuke_mesh: LoadAsset<Mesh> returned null"
                    : "timedNuke_mesh: " + loaded.name + " vertices=" + loaded.vertexCount + " submeshes=" + loaded.subMeshCount + " bounds=" + loaded.bounds.size);
            },
            assert: ctx =>
            {
                var loaded = timedNuke_meshLoaded;
                return loaded != null && loaded.name == "timedNuke_mesh" && loaded.vertexCount > 0 && loaded.triangles.Length > 0;
            },
            fail: "the game did not load timedNuke_mesh from the staged bundle"));

        Material timedNuke_matLoaded = null;
        queue.Add(CaseDef.Live(label, "load_timedNuke_mat", new[] { "bundle" },
            act: ctx =>
            {
                timedNuke_matLoaded = DataLoader.LoadAsset<Material>(Bundle + "?timedNuke_mat");
                var loaded = timedNuke_matLoaded;
                Report.Info(loaded == null
                    ? "timedNuke_mat: LoadAsset<Material> returned null"
                    : "timedNuke_mat: " + loaded.name + " shader=" + loaded.shader.name);
            },
            assert: ctx =>
            {
                var loaded = timedNuke_matLoaded;
                return loaded != null && loaded.name == "timedNuke_mat" && loaded.shader != null;
            },
            fail: "the game did not load timedNuke_mat from the staged bundle"));

        // A stem the bundle does not contain must still come back null, so a
        // pass above cannot be a loader that answers every request.
        Object absent = null;
        queue.Add(CaseDef.Live(label, "absent_stem_is_null", new[] { "bundle" },
            act: ctx =>
            {
                absent = DataLoader.LoadAsset<Object>(Bundle + "?shamwayAbsentStemProbe");
                Report.Info("absent_stem: " + (absent == null ? "null (expected)" : absent.name));
            },
            assert: ctx => absent == null,
            fail: "a stem the bundle does not contain resolved to an object"));
    }

    // A prefab hanging in front of the camera (*_look) and a block sitting on
    // a voxel (*_block_*) are different pictures. Mixing them in one
    // PLAYTEST_SUITE list is how a self-test rendered a texture mid-air AND a
    // placed block in the same session. Refuse it here, not after someone has
    // already watched both. The name is the picture: do not put a camera-staged
    // instantiate on a suite that is not named *_look so it can ride with a
    // block suite. A particle system that is already part of the staged prefab
    // is not a second picture.
    static void RejectMixedVisualSuites()
    {
        var raw = System.Environment.GetEnvironmentVariable("PLAYTEST_SUITE") ?? "";
        bool look = false, block = false;
        foreach (var token in raw.Split(new char[] { ',', ';', ' ', '\t' },
                     System.StringSplitOptions.RemoveEmptyEntries))
        {
            if (token.EndsWith("_look")) look = true;
            if (token.IndexOf("_block_", System.StringComparison.Ordinal) >= 0) block = true;
        }
        if (look && block)
        {
            throw new System.InvalidOperationException(
                "PLAYTEST_SUITE mixes a prefab-look suite (*_look) and a "
                + "block-placement suite (*_block_*); they are different pictures. "
                + "Run them as separate playtest invocations.");
        }
    }
}
