"""The agent-facing contract that ships into a consumer mod.

An agent doing asset work is working in the *mod's* repository, not in this
one, so the rules have to be there. `7dtd-assets init` writes this file to
`tools/7dtd-assets/AGENTS.md` inside the mod, where the agent will find it.
"""

from __future__ import annotations

AGENT_GUIDE = """# Asset pipeline: agent instructions

This mod builds its Unity asset bundle with
[7dtd-asset-pipeline](https://github.com/ywy50/7dtd-asset-pipeline). This file
is the contract for that work. It was generated by `7dtd-assets init`; edit it
freely to add mod-specific rules.

- Mod name (the `@modfolder` id): `{mod_name}`
- Bundle: `Resources/{bundle_name}`
- Unity project: `tools/7dtd-assets/UnityProject`
- Bundle membership: `tools/7dtd-assets/UnityProject/Assets/ModAssets/Bundle/`

## Orient before doing anything

```bash
7dtd-assets status --json
```

One call, never raises for a mod-state problem, and answers: does the bundle
exist, which Unity revision is it, does that match the installed game, does it
contain the required class-142 object, how many assets does the tracked
manifest list, which XML references exist, and is the mod currently valid.
Exit code 0 means valid. Start here rather than reading files.

## The commands

| Command | Cost | Effect |
|---|---|---|
| `7dtd-assets status --json` | instant | full state; no Unity, no network |
| `7dtd-assets capabilities --json` | instant | which optional tools work, and how to install them |
| `7dtd-assets doctor --json` | seconds | host readiness; exit 1 if any check is `FAIL` |
| `7dtd-assets refs` | instant | every bundle URI in `Config/**/*.xml` |
| `7dtd-assets inspect --json PATH` | fast | one bundle's revision and class IDs |
| `7dtd-assets inspect --deep PATH` | fast | every object and per-prefab components (UnityPy) |
| `7dtd-assets check-mesh FILE` | fast | authored-mesh extents and glTF conformance |
| `7dtd-assets validate` | fast | bundle + every XML reference |
| `7dtd-assets build --probe` | minutes | proves the environment; stages nothing |
| `7dtd-assets build` | minutes | **the only command that writes into this mod** |

Diagnose with the fast read-only commands. Reach for `build` only when an asset
actually changed.

## Optional capabilities

Some features need a tool the core does not require. Never guess whether one is
installed — ask, and act on the answer:

```bash
7dtd-assets capabilities --json          # what works now, and what unlocks what
7dtd-assets capabilities --missing       # only what is absent, with install commands
```

`status --json` also carries a `capabilities` map. Install everything with
`pip install 'sevendtd-asset-pipeline[all]'` plus, for Blender/OpenSCAD/glTF,
the pipeline's `scripts/install-tools.sh --with-authoring`.

## Making the assets

Two mesh lanes, both first-class — pick by what the shape needs:

- **authored**: Blender or OpenSCAD to `.glb`, checked with
  `7dtd-assets check-mesh` before import. Use for organic, rigged, or sculpted
  geometry.
- **procedural**: compose Unity's built-in primitives in the Unity project with
  `GeneratedAsset.Primitive(...)`. Use for hard-surface props. Emits no mesh
  asset at all, so the geometry stays a reviewable diff of numbers.

`GeneratedAsset` also builds materials with the shader keywords and transparent
blend state that a batch script otherwise silently omits.

## Rules

1. **Name every bundle asset with a unique, mod-prefixed stem.** 7DTD resolves
   assets by file-name stem alone, discarding folder and extension. Two assets
   sharing a stem make one of them unreachable; the build rejects that.
2. **Commit the `.meta` file with every source asset.** Unity identity lives in
   the `.meta`, and a missing one silently re-imports as a different asset.
3. **Commit the bundle and its tracked manifest together.** They are one
   logical artifact: `Resources/{bundle_name}` and
   `tools/7dtd-assets/manifests/{bundle_name}.manifest`.
4. **Declare the engine module for every component type you use.** Modules in
   `tools/7dtd-assets/UnityProject/Packages/manifest.json` are build inputs. An
   absent module makes Unity strip those classes while still reporting success.
   The pipeline refuses to stage such a build, but the fix is always here.
5. **Never write to the 7 Days to Die install.** It is read-only evidence.
6. **Never handle Unity credentials or licenses.** Sign-in is a human action.
7. **Offline gates are necessary, not sufficient.** Never report an asset as
   working, verified, or done on `build`/`validate` output alone. Acceptance
   is a fresh client that loads the asset by its real URI plus a human look or
   listen. Say plainly which of the two you did.

## Referencing an asset from XML

```xml
<property name="Model"
  value="#@modfolder({mod_name}):Resources/{bundle_name}?myAssetStem.prefab" />
```

The bare `@modfolder:` form also works and means this mod, but prefer the named
form: it fails loudly if the file is ever copied into a different mod.
`7dtd-assets validate` checks the mod name, bundle path, manifest membership,
and exact case of every such URI under `Config/`.

## When it fails

Read the error; each one names its own fix. Then:

```bash
7dtd-assets status --json
7dtd-assets inspect Resources/{bundle_name}
7dtd-assets inspect --deep Resources/{bundle_name}   # did the component survive?
7dtd-assets check-log .asset-pipeline/build/bundle/unity-build.log
```

Do not change compression, graphics APIs, or exporter shape speculatively. If
class 142 is missing, the cause is an engine module, not a build option.
"""


def render_agent_guide(mod_name: str, bundle_name: str) -> str:
    return AGENT_GUIDE.format(mod_name=mod_name, bundle_name=bundle_name)
