"""The agent-facing contract that ships into a consumer mod.

An agent doing asset work is working in the *mod's* repository, not in this
one, so the rules have to be there. `shamway init` writes this file to
`tools/shamway/AGENTS.md` inside the mod, where the agent will find it.
"""

from __future__ import annotations

AGENT_GUIDE = """# Asset pipeline: agent instructions

This mod builds its Unity asset bundle with **shamway**
([7dtd-asset-pipeline](https://github.com/ywy50/7dtd-asset-pipeline)). This
file is the contract for that work. It was generated by `shamway init`; edit it
freely to add mod-specific rules.

- Mod name (the `@modfolder` id): `{mod_name}`
- Bundle: `Resources/{bundle_name}`
- Unity project: `tools/shamway/UnityProject`
- Bundle membership: `tools/shamway/UnityProject/Assets/ModAssets/Bundle/`
- Editable sources and provenance: `assets-src/` (never ships)
- Item icons: `UIAtlases/ItemIconAtlas/` — **not** bundle assets

## Orient before doing anything

```bash
shamway status --json
```

One call, never raises for a mod-state problem, and answers: does the bundle
exist, which Unity revision is it, does that match the installed game, does it
contain the required class-142 object, how many assets does the tracked
manifest list, which XML references exist, and is the mod currently valid.
Exit code 0 means valid. Start here rather than reading files.

## The commands

| Command | Cost | Effect |
|---|---|---|
| `shamway status --json` | instant | full state; no Unity, no network |
| `shamway capabilities --json` | instant | which optional tools work, and how to install them |
| `shamway doctor --json` | seconds | host readiness; exit 1 if any check is `FAIL` |
| `shamway refs` | instant | every bundle URI in `Config/**/*.xml` |
| `shamway inspect --json PATH` | fast | one bundle's revision and class IDs |
| `shamway inspect --deep PATH` | fast | every object and per-prefab components (UnityPy) |
| `shamway check-mesh FILE` | fast | authored-mesh extents and glTF conformance |
| `shamway check-sound FILE` | fast | clip format, level, clipping, DC offset |
| `shamway check-icons` | instant | atlas cells and every `CustomIcon` key |
| `shamway validate` | fast | bundle + every XML reference |
| `shamway build --probe` | minutes | proves the environment; stages nothing |
| `shamway build` | minutes | builds, gates, and stages the bundle |
| `shamway render-icon STEM` | minutes | renders a prefab into its atlas cell |

Diagnose with the fast read-only commands. `build` and `render-icon` are the
only two that write into this mod; reach for them only when an asset actually
changed. `render-icon` needs a graphics device — run it under `xvfb-run -a` on
a headless host, because with `-nographics` Unity writes a blank image instead
of failing.

## Driving it programmatically

Do not scrape `--help`. The operation surface is published, and every operation
says what it costs, whether it writes, and what it needs:

```bash
shamway schema                       # every operation and its JSON Schema
shamway call status                  # run one, JSON in and out
shamway call build --params '{"probe":true}'
shamway serve                        # many operations in one process
```

`serve` reads one JSON request per line and writes one response per line
(`{"id":1,"op":"status"}` -> `{"id":1,"ok":true,"result":{...}}`). It refuses
operations that write files unless started with `--allow-writes`, so an
inspecting client cannot accidentally start a Unity build.

From Python:

```python
from sevendtd_asset_pipeline import Pipeline
pipeline = Pipeline.discover()
if not pipeline.status().valid:
    pipeline.build()
    pipeline.validate()
```

## The generators and the docs live in the tool, not in this mod

Never copy a script out of the pipeline into this repository, and never write a
relative path into a checkout of it. Everything generalized is reachable from
the command this mod already depends on:

```bash
shamway generate --list                  # sound, audio, cutout, icon, texture-maps, mesh
shamway generate sound --help            # each one explains itself
shamway generate sound blast assets-src/audio/blast.wav --seed 7
shamway docs                             # every rule the pipeline knows
shamway docs art-direction               # the style contract, in full
```

What belongs in *this* repository is the content: `Config/`, `UIAtlases/`, the
Unity assets and their `.meta` files, the built bundle and its manifest, and
everything under `assets-src/` — the prompts, seeds, and commands that produced
the art. `shamway docs mod-repo-layout` is the full split.

If a generator here is not enough, write a mod-specific one in `assets-src/`
following the same contract (explicit paths, recorded seed, printed numbers,
atomic writes). Keep it in this mod.

## Optional capabilities

Some features need a tool the core does not require. Never guess whether one is
installed — ask, and act on the answer:

```bash
shamway capabilities --json          # what works now, and what unlocks what
shamway capabilities --missing       # only what is absent, with install commands
```

`status --json` also carries a `capabilities` map. Install everything with
`uv pip install '7dtd-asset-pipeline[all]'` plus, for Blender/OpenSCAD/glTF,
the pipeline's `scripts/install-tools.sh --with-authoring`.

## Making the assets

Author sources in `assets-src/`, then copy only the **selected** output into the
Unity bundle folder. Read `assets-src/README.md` — it says what provenance each
asset owes. The pipeline's own docs carry the lane detail: `docs/art-direction.md`
for anything generated or drawn, `docs/audio.md` for sound, `docs/vfx.md` for
particle effects.

**Meshes — two lanes, both first-class.** Pick by what the shape needs:

- **authored**: Blender or OpenSCAD to `.glb`, checked with
  `shamway check-mesh` before import. Use for organic, rigged, or sculpted
  geometry.
- **procedural**: compose Unity's built-in primitives in the Unity project with
  `GeneratedAsset.Primitive(...)`. Use for hard-surface props. Emits no mesh
  asset at all, so the geometry stays a reviewable diff of numbers.

**Icons — two lanes, both first-class.** Generated or drawn art when the icon
should show something the mesh does not; `shamway render-icon STEM` when the
icon should *be* the item, which is the only way it cannot drift from the mesh.
Icons are 160 x 160 RGBA cells in `UIAtlases/ItemIconAtlas/`, keyed by filename
stem, packed at runtime — they never enter the bundle, so `validate` cannot see
them and `check-icons` exists for them.

**Sound.** `shamway generate sound` synthesizes designed voices from a
recorded seed and prints the matching `sounds.xml` entry;
`check-sound` gates the file. A clip that loads can still be inaudible — an
AudioSource prefab's `maxDistance` decides that — so read `docs/audio.md` before
wiring a long-range sound.

`GeneratedAsset` also builds materials, texture imports, particle blend state,
and audio imports with the settings a batch script otherwise silently omits.

## Rules

1. **Name every bundle asset with a unique, mod-prefixed stem.** 7DTD resolves
   assets by file-name stem alone, discarding folder and extension. Two assets
   sharing a stem make one of them unreachable; the build rejects that.
2. **Commit the `.meta` file with every source asset.** Unity identity lives in
   the `.meta`, and a missing one silently re-imports as a different asset.
3. **Commit the bundle and its tracked manifest together.** They are one
   logical artifact: `Resources/{bundle_name}` and
   `tools/shamway/manifests/{bundle_name}.manifest`.
4. **Declare the engine module for every component type you use.** Modules in
   `tools/shamway/UnityProject/Packages/manifest.json` are build inputs. An
   absent module makes Unity strip those classes while still reporting success.
   The pipeline refuses to stage such a build, but the fix is always here.
5. **Exclude inherited properties, do not just omit them.** `ItemClassesFromXml`
   and `BlocksFromXml` copy every parent property the `Extends` `param1` list
   does not name, so deleting a `TintColor`, `Meshfile`, `Model`, or
   `CustomIcon` line does not stop the parent's value applying. Name it in
   `param1` on anything that owns its own art.
6. **Never write to the 7 Days to Die install.** It is read-only evidence.
7. **Never handle Unity credentials or licenses.** Sign-in is a human action.
8. **Offline gates are necessary, not sufficient.** Never report an asset as
   working, verified, or done on `build`/`validate` output alone. Acceptance
   is a fresh client that loads the asset by its real URI plus a human look or
   listen. Say plainly which of the two you did.

## Referencing an asset from XML

```xml
<property name="Model"
  value="#@modfolder({mod_name}):Resources/{bundle_name}?myAssetStem.prefab" />
```

The bare `@modfolder:` form also works and means this mod, but prefer the named
form: it fails loudly if the file is ever copied into a different mod.
`shamway validate` checks the mod name, bundle path, manifest membership,
and exact case of every such URI under `Config/`.

## When it fails

Read the error; each one names its own fix. Then:

```bash
shamway status --json
shamway inspect Resources/{bundle_name}
shamway inspect --deep Resources/{bundle_name}   # did the component survive?
shamway check-log .shamway/build/bundle/unity-build.log
```

Silent failures worth knowing before you chase one: a missing icon draws
whatever else answers to its key, a missing model draws a fallback mesh, an
unknown sound group simply never plays, a script-built material renders flat or
opaque when its shader keyword or blend state was never set, and an inherited
`TintColor` quietly recolours authored paint. None of them produce an error.

Do not change compression, graphics APIs, or exporter shape speculatively. If
class 142 is missing, the cause is an engine module, not a build option.
"""


def render_agent_guide(mod_name: str, bundle_name: str) -> str:
    """Fill the guide's placeholders.

    Deliberately not `str.format`: this document contains JSON examples, and
    every brace in them would have to be doubled, which is a trap that breaks
    scaffolding the moment someone adds an example without noticing.
    """
    return AGENT_GUIDE.replace("{mod_name}", mod_name).replace("{bundle_name}", bundle_name)
